# Generated by Django 6.0.3 on 2026-03-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oseba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ime in Priimek', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Oznaka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kratica', models.CharField(max_length=10)),
            ],
        ),
    ]
