# Generated by Django 6.0.3 on 2026-03-12 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmiapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oseba',
            old_name='Ime in Priimek',
            new_name='ime',
        ),
    ]
