# Generated by Django 6.0.3 on 2026-03-12 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmiapp', '0002_rename_ime_in_priimek_oseba_ime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zanr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=50, unique=True, verbose_name='Naziv žanra')),
            ],
        ),
        migrations.RemoveField(
            model_name='oznaka',
            name='id',
        ),
        migrations.AlterField(
            model_name='oseba',
            name='ime',
            field=models.CharField(max_length=100, verbose_name='Ime in priimek'),
        ),
        migrations.AlterField(
            model_name='oznaka',
            name='kratica',
            field=models.CharField(help_text='Kratica za oznako filma, npr. PG', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=200, verbose_name='Naslov filma')),
                ('dolzina', models.PositiveIntegerField(verbose_name='Dolžina filma v minutah')),
                ('leto', models.PositiveSmallIntegerField(verbose_name='Leto izida filma')),
                ('ocena', models.FloatField(verbose_name='Ocena filma')),
                ('metascore', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('glasovi', models.IntegerField(default=0, verbose_name='Število glasov za film')),
                ('zasluzek', models.BigIntegerField(blank=True, null=True, verbose_name='Zaslužek filma (USD)')),
                ('opis', models.CharField(blank=True, help_text='Opis filma, do 1000 znakov', max_length=1000, null=True, verbose_name='Opis filma')),
                ('oznaka', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filmiapp.oznaka', verbose_name='Oznaka filma')),
            ],
        ),
        migrations.CreateModel(
            name='Vloga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmiapp.film')),
                ('oseba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmiapp.oseba')),
            ],
        ),
    ]
