# Generated by Django 6.0.3 on 2026-03-12 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmiapp', '0003_zanr_remove_oznaka_id_alter_oseba_ime_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vloga',
        ),
    ]
