# Generated by Django 4.2.11 on 2026-03-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmiapp', '0004_delete_vloga'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film',
            options={'verbose_name_plural': 'Filmi'},
        ),
        migrations.AlterModelOptions(
            name='oseba',
            options={'verbose_name_plural': 'Osebe'},
        ),
        migrations.AlterModelOptions(
            name='oznaka',
            options={'ordering': ['kratica'], 'verbose_name_plural': 'Oznake'},
        ),
        migrations.AlterModelOptions(
            name='zanr',
            options={'verbose_name_plural': 'Žanri'},
        ),
        migrations.AlterField(
            model_name='film',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='film',
            name='ocena',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Ocena filma'),
        ),
        migrations.AlterField(
            model_name='oseba',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='zanr',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
