# Generated by Django 6.0.3 on 2026-03-19 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmiapp', '0005_alter_film_options_alter_oseba_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='zanri',
            field=models.ManyToManyField(to='filmiapp.zanr', verbose_name='Žanri, katerim film ustreza'),
        ),
        migrations.AlterField(
            model_name='film',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='oseba',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='zanr',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Vloga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesto', models.PositiveIntegerField()),
                ('tip', models.CharField(choices=[('I', 'Igralec'), ('R', 'Režiser')], max_length=20)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmiapp.film')),
                ('oseba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmiapp.oseba')),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='vloge',
            field=models.ManyToManyField(through='filmiapp.Vloga', to='filmiapp.oseba'),
        ),
        migrations.AddConstraint(
            model_name='vloga',
            constraint=models.UniqueConstraint(fields=('film', 'mesto', 'tip'), name='enoličnost_sodelujočega_v_filmu'),
        ),
    ]
