# Generated by Django 6.0.3 on 2026-03-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmiapp', '0006_film_zanri_alter_film_id_alter_oseba_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='zanri',
            field=models.ManyToManyField(to='filmiapp.zanr', verbose_name='Žanri filma'),
        ),
    ]
