# Generated by Django 6.0.3 on 2026-03-24 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmiapp', '0007_alter_film_zanri'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vloga',
            options={'verbose_name_plural': 'Vloge'},
        ),
    ]
