# Generated by Django 6.0.3 on 2026-04-09 00:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmiapp', '0010_alter_film_id_alter_oseba_id_alter_vloga_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='glasovalci',
            field=models.ManyToManyField(related_name='glasovani_filmi', through='filmiapp.Glas', to=settings.AUTH_USER_MODEL),
        ),
    ]
