# Generated by Django 6.0.3 on 2026-04-10 13:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmiapp', '0011_film_glasovalci'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Glas',
            new_name='DaniGlasovi',
        ),
        migrations.RemoveField(
            model_name='film',
            name='glasovalci',
        ),
    ]
