# Generated by Django 6.0.3 on 2026-04-23 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmiapp', '0012_rename_glas_daniglasovi_remove_film_glasovalci'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='daniglasovi',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obstojeci_glasovi', to='filmiapp.film'),
        ),
        migrations.AlterField(
            model_name='daniglasovi',
            name='uporabnik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obstojeci_glasovi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='daniglasovi',
            index=models.Index(fields=['uporabnik', 'film'], name='filmiapp_da_uporabn_23232a_idx'),
        ),
    ]
